"""Shared constants for scripts."""

POSTS_DATA_FILE = "posts_data.json"
STATUS_EXCEEDS_LIMIT = "EXCEEDS LIMIT"
STATUS_NEAR_LIMIT = "NEAR LIMIT"
SEO_DESCRIPTION_LIMIT = 140
SEO_DESCRIPTION_WARNING = 145
