name: Add Single Post

on:
  workflow_dispatch:
    inputs:
      post_slug:
        description: 'The URL slug of the dev.to post to add'
        required: true

permissions:
  contents: write

jobs:
  add_post:
    if: github.ref != 'refs/heads/gh-pages'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests jinja2 python-slugify

      - name: Add post using slug
        env:
          DEVTO_USERNAME: ${{ vars.DEVTO_USERNAME }}
          PAGES_REPO: ${{ github.repository }}
        run: python scripts/add_post.py "${{ github.event.inputs.post_slug }}"

      - name: Commit & push changes to gh-pages
        run: |
          set -e
          git config user.name "ci-bot"
          git config user.email "actions@users.noreply.github.com"

          # Ensure we have the remote branch info
          git fetch --all --prune

          if git rev-parse --verify origin/gh-pages >/dev/null 2>&1; then
            echo "gh-pages exists on remote, checking out"
            git checkout gh-pages
            git reset --hard origin/gh-pages
          else
            echo "gh-pages does not exist, creating orphan branch"
            git checkout --orphan gh-pages
            git rm -rf .
          fi

          # Run the add_post script again, this time on the gh-pages branch
          # The script is idempotent, so it's safe to run again.
          # It will add the post to the correct posts_data.json and create the html file.
          python scripts/add_post.py "${{ github.event.inputs.post_slug }}"

          # Regenerate index and sitemap to include the new post
          if [ -f "scripts/render_index_sitemap.py" ]; then
            python scripts/render_index_sitemap.py
          else
            echo "Warning: render_index_sitemap.py not found; skipping index/sitemap regeneration" >&2
          fi

          git add posts_data.json posts/ index.html sitemap.xml
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "feat: add post ${{ github.event.inputs.post_slug }}"
            git push origin gh-pages
          fi
