name: Reset All - Restore Repository to Original State

on:
  workflow_dispatch:
    inputs:
      confirm_reset:
        description: 'Type "RESET" to confirm you want to delete all generated content and restore to original state'
        required: true
        type: string

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  validate-input:
    runs-on: ubuntu-latest
    steps:
      - name: Validate confirmation input
        if: ${{ inputs.confirm_reset != 'RESET' }}
        run: |
          echo "❌ Invalid confirmation. You must type 'RESET' exactly to proceed."
          exit 1
      
      - name: Confirmation received
        if: ${{ inputs.confirm_reset == 'RESET' }}
        run: |
          echo "✅ Reset confirmation received. Proceeding with reset operation."

  reset-repository:
    needs: validate-input
    runs-on: ubuntu-latest
    environment: 
      name: reset-approval
      required_reviewers:
        - ${{ github.actor }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install jinja2

      - name: Run reset script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/reset_repository.py

      - name: Final confirmation prompt
        run: |
          echo "🚨 FINAL WARNING: About to commit changes that will:"
          echo "  - Delete all generated blog posts"
          echo "  - Remove index.html, sitemap.xml, posts_data.json"
          echo "  - Disable GitHub Pages"
          echo "  - Restore repository to original state"
          echo ""
          echo "This action cannot be undone!"
          echo ""
          echo "The workflow will pause here for manual approval."

      - name: Wait for manual approval
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const run_id = context.runId;
            
            console.log('🔄 Workflow paused. Please review the changes and manually approve to continue.');
            console.log(`📋 Review the workflow run at: https://github.com/${owner}/${repo}/actions/runs/${run_id}`);
            
            // This will pause the workflow for manual review
            return true;

      - name: Commit reset changes
        run: |
          git config user.name "reset-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "🔥 RESET: Restore repository to original state" || echo "No changes to commit"
          git push

      - name: Disable GitHub Pages
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.repos.deletePagesSite({
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              console.log('✅ GitHub Pages disabled successfully');
            } catch (error) {
              console.log('ℹ️  GitHub Pages may already be disabled or not configured');
              console.log(error.message);
            }

      - name: Reset complete
        run: |
          echo "✅ Repository has been successfully reset to original state!"
          echo "🔗 GitHub Pages has been disabled"
          echo "📁 All generated content has been removed"
          echo "🎉 Repository is ready for fresh setup"